// <auto-generated />
namespace AdminHotelApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class M12052022 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M12052022));
        
        string IMigrationMetadata.Id
        {
            get { return "202205130359137_M12052022"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
