// <auto-generated />
namespace AdminHotelApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class M21062022 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M21062022));
        
        string IMigrationMetadata.Id
        {
            get { return "202206220348458_M21062022"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
